# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REACT_APP_API_KEY: ${{secrets.REACT_APP_API_KEY}}
  SPOTIFY_CLIENT_ID: ${{secrets.SPOTIFY_CLIENT_ID}}
  SPOTIFY_CLIENT_SECRET: ${{secrets.SPOTIFY_CLIENT_SECRET}}
  SPOTIFY_CALLBACK_URL: ${{secrets.SPOTIFY_CALLBACK_URL}}
  BASE_URL: ${{secrets.BASE_URL}}
  DB_HOST: ${{secrets.DB_HOST}}
  DB_USER: ${{secrets.DB_USER}}
  DB_NAME: ${{secrets.DB_NAME}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  REACT_APP_MP_PROJECT_TOKEN: ${{secrets.REACT_APP_MP_PROJECT_TOKEN}}
  NODE_ENV: ${{secrets.NODE_ENV}}
  SESSION_KEYS: ${{secrets.SESSION_KEYS}}
  TWILIO_ACCOUNT_ID: ${{secrets.TWILIO_ACCOUNT_ID}}
  TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
  TWILIO_SERVICE_ID: ${{secrets.TWILIO_SERVICE_ID}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: CI=false yarn build
